[package]
name = "modbus-impl"
version = "0.7.0"
edition = "2021"
rust-version = "1.77"
documentation = "https://docs.rs/modbus-impl"
readme = "README.md"
authors = ["sndnvaps <admin@sndnvaps.com>"]
description = "A small `no_std` Modbus RTU helper library designed to run on embedded Rust targets"
build = false
autolib = false
keywords = [
    "embedded-hal",
    "modbus",
    "modbus-rtu",
    "no-std",
]
categories = [
    "embedded",
    "hardware-support",
    "no-std",
]
license = "MIT OR Apache-2.0"
repository = "https://github.com/sndnvaps/modbus-impl"

[package.metadata.docs.rs]
targets = ["thumbv6m-none-eabi"]


[lib]
name = "modbus_impl"
path = "src/lib.rs"

